---
- name: Install Nginx Web Server on Ubuntu
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx systemd

- name: Replace nginx.conf
  template:
    src=/etc/ansible/roles/newrole/files/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
  - Restart nginx

- name: Replace index.html
  template:
    src=/etc/ansible/roles/newrole/files/index.html
    dest=/var/www/public
